# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-06 10:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobby',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('backing', 'baking'), ('chess', 'chess'), ('drawing', 'drawing'), ('music', 'music'), ('sports', 'sports')], default='backing', max_length=10), size=None),
        ),
    ]
