# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-07 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0007_auto_20190207_1507'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
