# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-11 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_auto_20190207_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
